import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { BotIcon as LogoIcon } from "lucide-react";
import Link from "next/link";
import { ThemeProvider } from "next-themes";

import * as workspaceAction from "@/actions/domain/workspace";

import { Toaster } from "@/components/ui/sonner";

import SwitchingTheme from "@/components/shared/switchingTheme";
import Tracking from "@/components/shared/tracking";
import WorkspaceSelector from "@/components/shared/workspaceSelector";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = await auth();

  let workspaces: Awaited<ReturnType<typeof workspaceAction.findMany>> = [];

  if (userId != null) {
    workspaces = await workspaceAction.findMany();
  }

  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <div className="m-auto max-w-3xl">
              <header className="p-8 font-mono">
                <div className="grid grid-flow-col grid-cols-[auto_1fr]">
                  <div>
                    <Link href="/">
                      <LogoIcon size={32} />
                    </Link>
                  </div>
                  <div className="grid grid-flow-col items-center justify-end gap-4">
                    <Show when="signed-in">
                      {workspaces.length > 0 && (
                        <WorkspaceSelector workspaces={workspaces} />
                      )}
                    </Show>
                    <SwitchingTheme />
                    <div className="flex items-center gap-2">
                      <Show when="signed-out">
                        <SignInButton />
                        <SignUpButton />
                      </Show>
                      <Show when="signed-in">
                        <UserButton />
                      </Show>
                    </div>
                  </div>
                </div>
              </header>
              <div className="min-h-lvh p-8 font-mono">{children}</div>
              <footer className="p-8 font-mono text-xs">
                <div className="grid grid-flow-col grid-cols-[auto_1fr]">
                  <div className="grid grid-flow-col gap-4">
                    <div>
                      <Link href="#">Privacy Policy</Link>
                    </div>
                    <div>
                      <Link href="#">Terms of Service</Link>
                    </div>
                  </div>
                </div>
              </footer>
            </div>
            <Tracking gaId={process.env.NEXT_PUBLIC_GA_ID} />
            <Toaster />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
